[package]
name = "tms"
version = "0.0.0"
edition = "2021"
license = "MIT"
readme = "README.md"
categories = ["asynchronous"]
keywords = ["api","teams"]
authors = ["Willy Micieli"]
repository="https://github.com/otechdo/tms"
description = "The teams api"
[dependencies]
actix-web = "4.8.0"
